add cinema ticket files to repository
olalipa/cinema pull request #1
Opened 2024-11-17 23:39 UTC by olalipa

2024-11-18 17:44 UTC, Solnick requested changes
<img width="1765" alt="image" src="https://github.com/user-attachments/assets/d7e890b4-f12c-48f0-ba6c-0dae0e34929f">
I think the font sizes are different. Please check in figma what font size to use.

2024-11-18 17:44 UTC, Solnick commented on index.html
> +        <div class="seat"> SEAT: B43</div>
```suggestion
        <div class="seat">SEAT: B43</div>
```
Don't add redundant spaces

2024-11-18 17:44 UTC, Solnick commented on index.html
> +      </div>
```suggestion
      <div class="ticket-number">TICKET NO: 103752</div>
```
This new line is not needed

2024-11-18 17:44 UTC, Solnick commented on style.css
> +    font-family: Roboto;
remember about adding fallback font

2024-11-18 17:44 UTC, Solnick commented on style.css
> +    margin-right: 63px;
When using margin or padding make sure that the values ar multiplication of the same number, usually it is a multiplication of 4px. It makes elements positioning and aligning a lot easier

2024-11-18 17:46 UTC, Solnick requested changes

2024-11-18 17:46 UTC, Solnick commented on style.css
> +    margin-right: 63px;
Using such a big margin value is always a red flag. Probably you can achieve the same effect by making the parent component bigger and setting up the flexbox align/justify-content.

2024-11-25 16:50 UTC, Solnick requested changes
Please change the code according to the comments. You ignored the comments about: 1. big padding and margins
2. spacing should be multiplication of 4px

2024-11-25 21:04 UTC, olalipa commented
> Please change the code according to the comments. You ignored the comments about: 1. big padding and margins 2. spacing should be multiplication of 4px

I am not sure if I get you comment correctly.. I already changed big margin (63 px) last time. Regarding spacing that should be multiplication of 4px - why is 20 px incorrent in this case?

2024-12-06 11:36 UTC, Solnick approved these changes

2024-12-10 11:48 UTC, merged